import './styles/globals.css'
import Navigation from './ui/Navigation/Navigation'
import ClientHelpers from './ui/ClientHelpers'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next Docs',
  description: 'Generated by myself 🌟🌠'
}

function RootLayout({ children }) {

  const clickingSound = () => {
    console.log('clicked!')
  }

  return (
    // NE RADI SMOOTH SCROLL IZ NEKOG RAZLOGA, CAK NI SA ONIM SCROLL={FALSE}
    <html lang='en' className='scroll-smooth'>
      <body className='min-h-screen text-white bg-[#404040]'>
        <ClientHelpers />
        <Navigation />
        {children}
      </body>
    </html>
  )
}

export default RootLayout

// Root Layout MORA da bude SERVER komponenta i mora da ima html i body tagove, a nijedan drugi NE SME da ima html i body sem ovog.
